version: 2
jobs:
  build_python3:
    docker:
      - image: circleci/python:3.6.8

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "setup.py" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-test.txt

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "setup.py" }}
        
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python setup.py test

  build_python2:
    docker:
      - image: circleci/python:2.7.16

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}

      - run:
          name: install dependencies
          command: |
            sudo python2 -m virtualenv venv
            . venv/bin/activate
            sudo pip install -r requirements-test.txt

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "setup.py" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            sudo python setup.py test

  deploy:
    docker:
      - image: circleci/python:3.6.8

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}
         
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-test.txt

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "setup.py" }}

      - run:
          name: verify git tag vs. version
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py verify


      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USER" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

      - run:
          name: create packages
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pandoc
            pip install wheel
            python setup.py sdist
            python setup.py bdist_wheel

      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            pip install twine
            twine upload dist/*
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build_python3
      - build_python2
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
